export const PRODUCT_NAME = 'PRODUCT_NAME';
export const PRODUCT_PRICED =  'PRODUCT_PRICED';
export const PRODUCT_QUATITY = 'PRODUCT_QUATITY';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const NEW_PRODUCT_ADDED = 'NEW_PRODUCT_ADDED';